In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
!ls "/content/drive/My Drive/AI70/ai73"

In [ ]:
from numpy import unicode_
import pandas as pd
dfSongName = pd.read_csv('/content/drive/My Drive/AI70/ai73/lyric_thai.csv')

In [ ]:
import requests
from bs4 import BeautifulSoup
from urllib.request import urlopen, Request
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.3'}

In [ ]:
df_Lyrics = pd.DataFrame(columns=['Song','Singer','Lyrics'])

ลิ้งไปยังเว็บเนื้อเพลง https://www.siamzone.com/music/thailyric/index.php?mode=allartist


In [ ]:
for i in  dfSongName.loc[:,'link-href']:
  quote_page = i
  req = Request(url=quote_page, headers = headers)
  page = urlopen(req).read()
  soup = BeautifulSoup(page,'html.parser')

  lyrics = soup.find('div', attrs = {'class':'has-text-centered-mobile is-size-5-desktop'}).find(style = 'margin-bottom: 1rem;')
  title = soup.find('title')

  lyrics.text.replace("\t", "").replace("\r", "").replace("\n", " ")
  a=[]
  a = title.text.split(" | ")
  singer = a[1]
  b = a[0].split(" ")
  song = b[1]
  
  df = pd.DataFrame(columns=['Song','Singer','Lyrics'])
  df = df.append({'Song': song,'Singer': singer,'Lyrics': lyrics.text.replace("\t", "").replace("\r", "").replace("\n", " ")}, ignore_index=True)

  df_Lyrics = pd.concat([df_Lyrics, df])
  import time
  time.sleep(2)

In [ ]:
df_Lyrics

Song                       Singer  \
0                   นุ่มนวล        แน็ท ศิริพงษ์ ศรีสุขา   
0           สัจธรรมความเจ็บ  เอิร์ธ พิชิตพงษ์ คำบุญเหลือ   
0                       Hot              พิกซ์ซี่ Pixxie   
0         ไม่ต้องการจะหายไป          ออเดอร์ 41 Order 41   
0                    คนจะลา                     มีน Mean   
..                      ...                          ...   
0   ความสัมพันธ์ที่บ่มีชื่อ                   อาม ชุติมา   
0            ได้ใหม่ลืมเก่า                  วุฒิ ป่าบอน   
0          แด่ฉันในวัยเยาว์              บ้านข้างๆ t_047   
0                     งานศพ              บ้านข้างๆ t_047   
0      สายธารที่ไหลกลับบ้าน              บ้านข้างๆ t_047   

                                               Lyrics  
0    ละมุนงามหลาย ผิวนวลตาคม กลิ่นเจ้าเมื่อได้ดมดั...  
0    ตั้งแต่จบปลายตัวเฮา 2 คนกะบ่ได้พ้อกัน เหลือแต...  
0    Hey คนนั้นคือเธอใช่มะ ได้ยินที่เค้าพูดกันว่าเ...  
0    I'm a stoner tonight And see you walk by Want...  
0    ถ้าคนจะลาก็คือลา คนจะไปก็คือไป ก็ไหนๆ ทำฉันเส...  
..                                                ...  
0    คิดฮอดกะมาหา เบิดค่ากะจากไป ตั๋วว่าคิดฮอดตั๋ว...  
0    คนไม่รู้จักพอ ให้ดีเท่าไรก็คงไม่พอใจ หรือต้อง...  
0    แด่ฉันในวัยเยาว์ แด่ฝันในวันเก่า วันนึงเธอจะพ...  
0    เธอยังเสียใจอยู่ไหม เธอยังร้องไห้รึเปล่า ในวั...  
0    เหมือนดวงดาวนั้นเป็นดวงตา คล้ายดวงจันทร์นั้นเ...  

[915 rows x 3 columns]

ติดตั้ง library แยกคำไทย

In [ ]:
! pip install pythainlp
!pip install epitran
!pip install sklearn_crfsuite
!pip install tensorflow deepcut
!pip install attacut


In [ ]:
!pip install xlrd #อ่าน excel

In [ ]:
import pythainlp #แยกคำไทย
!wget https://github.com/Phonbopit/sarabun-webfont/raw/master/fonts/thsarabunnew-webfont.ttf


In [ ]:
dfLabel = pd.read_excel('/content/drive/My Drive/AI70/ai73/Lyric_Label.xlsx')

In [ ]:
dfLabel

Lyrics       Label
0     ละมุนงามหลาย ผิวนวลตาคม กลิ่นเจ้าเมื่อได้ดมดั...         จีบ
1     ตั้งแต่จบปลายตัวเฮา 2 คนกะบ่ได้พ้อกัน เหลือแต...       อกหัก
2     Hey คนนั้นคือเธอใช่มะ ได้ยินที่เค้าพูดกันว่าเ...    สนุกสนาน
3     I'm a stoner tonight And see you walk by Want...       อกหัก
4     ถ้าคนจะลาก็คือลา คนจะไปก็คือไป ก็ไหนๆ ทำฉันเส...       อกหัก
..                                                 ...         ...
905   คนไม่รู้จักพอ ให้ดีเท่าไรก็คงไม่พอใจ หรือต้อง...     ผิดหวัง
906   แด่ฉันในวัยเยาว์ แด่ฝันในวันเก่า วันนึงเธอจะพ...  ให้กำลังใจ
907   เธอยังเสียใจอยู่ไหม เธอยังร้องไห้รึเปล่า ในวั...  ให้กำลังใจ
908   เหมือนดวงดาวนั้นเป็นดวงตา คล้ายดวงจันทร์นั้นเ...         จีบ
909  รู้จักยังสัสกูไม้โท ราชาเหินออกตัวแบบฉายเดี่ยว...    สนุกสนาน

[910 rows x 2 columns]

In [ ]:
from pythainlp import sent_tokenize, word_tokenize

In [ ]:
ForWord = pd.DataFrame(columns=['Lyrics', 'Label'])

**แยกคำ**

In [ ]:
x = 0
for i in dfLabel.loc[:,'Lyrics']:
  ForWord = ForWord.append({'Lyrics': word_tokenize(i, keep_whitespace=False),'Label': dfLabel.loc[x,'Label']}, ignore_index = True)
  x = x+1

In [ ]:
ForWord

Lyrics       Label
0    [ละมุน, งาม, หลาย, ผิว, นวล, ตาคม, กลิ่น, เจ้า...         จีบ
1    [ตั้งแต่, จบ, ปลาย, ตัว, เฮา, 2, คน, กะ, บ่, ไ...       อกหัก
2    [Hey, คน, นั้น, คือ, เธอ, ใช่, มะ, ได้ยิน, ที่...    สนุกสนาน
3    [I, ', m, a, stoner, tonight, And, see, you, w...       อกหัก
4    [ถ้า, คน, จะ, ลา, ก็, คือ, ลา, คน, จะ, ไป, ก็,...       อกหัก
..                                                 ...         ...
905  [คน, ไม่, รู้จัก, พอ, ให้, ดี, เท่าไร, ก็, คง,...     ผิดหวัง
906  [แด่, ฉัน, ใน, วัยเยาว์, แด่, ฝัน, ใน, วัน, เก...  ให้กำลังใจ
907  [เธอ, ยัง, เสียใจ, อยู่, ไหม, เธอ, ยัง, ร้องไห...  ให้กำลังใจ
908  [เหมือน, ดวงดาว, นั้น, เป็น, ดวงตา, คล้าย, ดวง...         จีบ
909  [รู้จัก, ยัง, สัส, กู, ไม้โท, ราชา, เหิน, ออกต...    สนุกสนาน

[910 rows x 2 columns]

In [ ]:
ForWord.to_excel('ForWord.xlsx')

---------------------------------------------------------


**ช่วงการทดลองสร้าง** **dataset**

In [ ]:
ForWord_Sub1 = pd.DataFrame()

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
word_tokenize(dfLabel.loc[0,'Lyrics'], keep_whitespace=False)

In [ ]:
' '.join(word_tokenize(dfLabel.loc[0,'Lyrics'], keep_whitespace=False))

'ละมุน งาม หลาย ผิว นวล ตาคม กลิ่น เจ้า เมื่อ ได้ ดม ดั่ง ดวง จำปา ละมุน จริงใจ คือ สำเนียง ภาษา ดีใจ ที่ อ้าย ได้มา มา พบ พ้อ เจ้า แม่น้ำ โขง คั่น เฮา ไว้ แต่ บ่ เคย กั้น ใจ ให้ ใจ สอง เฮา ได้ คึด ฮอด กัน แววตา เจ้า นั้น อ้าย ยัง จำ สัมพันธ์ อยู่ เมือง เวียงจันทน์ ท่ามกลาง ประตู ไซ อยาก ไป เยี่ยม ยาม ถาม ว่า สำ บาย ดี บ่ อ้าย คน บ่ หล่อ อยาก สิ ไป ถามไถ่ ให้ เจ้า ไข หัวใจ ฮับ ฮัก อ้าย แน่ หอม รัญจวน กลิ่น นวล น้อง นาง แวว ตาหวาน อ้าย ซวน ซื่นซม อยาก กอด น้อง นาง เอวบาง ตากลม อ้าย หลง ซื่นซม น้อง คำ นาง ตก แลง ยาม ค่ำ เหลี่ยว เบิ่ง ตะ เว็น คึด ฮอด บ่ ว่างเว้น คึด พ้อ ลาย ซิ่น คน งาม จิบ เบย ลาว คืน นั้น มื้อ ที่ เจ้า เคียงข้าง อยาก ให้ นิยาม ว่า น้อง นาง นุ่มนวล หอม รัญจวน กลิ่น นวล น้อง นาง แวว ตาหวาน อ้าย ซวน ซื่นซม อยาก กอด น้อง นาง เอวบาง ตากลม อ้าย หลง ซื่นซม น้อง คำ นาง อ้าย หลง ซื่นซม น้อง นาง นุ่มนวล อ้าย หลง ซื่นซม น้อง นาง นุ่มนวล'

In [ ]:
def my_tokenise(txt):
  txt = word_tokenize(txt, keep_whitespace=False)
  return ' '.join(txt)

In [ ]:
ForWord_Sub1['token'] = dfLabel.loc[:,'Lyrics'].apply(my_tokenise)

In [ ]:
ForWord_Sub1

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer


vectorizer = CountVectorizer()
X = vectorizer.fit_transform(ForWord_Sub1.loc[:,'token'])

print(X.shape)
print(X.toarray())
print(vectorizer.get_feature_names_out())
dfX = pd.DataFrame(X.toarray())

In [ ]:
dfX = pd.DataFrame(X.toarray())

In [ ]:
dfX

0     1     2     3     4     5     6     7     8     9     ...  7396  \
0       0     0     0     0     0     0     0     0     0     0  ...     0   
1       0     0     0     0     0     0     0     0     0     0  ...     0   
2       0     0     0     0     0     0     0     0     0     0  ...     0   
3       0     0     0     0     0     0     0     0     0     0  ...     0   
4       0     0     0     0     0     0     0     0     0     0  ...     0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
905     0     0     0     0     0     0     0     0     0     0  ...     0   
906     0     0     0     0     0     0     0     0     0     0  ...     0   
907     0     0     0     0     0     0     0     0     0     0  ...     0   
908     0     0     0     0     0     0     0     0     0     0  ...     0   
909     0     0     0     0     0     0     0     0     0     0  ...     0   

     7397  7398  7399  7400  7401  7402  7403  7404  7405  
0       0     0     0     0     0     0     0     0     0  
1       0     0     0     0     0     0     0     0     0  
2       0     0     0     0     0     0     0     0     0  
3       0     0     0     0     0     0     0     0     0  
4       0     0     0     0     0     0     0     0     0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
905     0     0     0     0     0     0     0     0     0  
906     0     0     0     0     0     0     0     0     0  
907     0     0     0     0     0     0     0     0     0  
908     0     0     0     0     0     0     0     0     0  
909     0     0     0     0     0     0     0     0     0  

[910 rows x 7406 columns]

In [ ]:
dfX.to_excel('dfX.xlsx')

In [ ]:
dfX['Label'] = dfLabel.loc[:,'Label']

Decition Tree

In [ ]:
from sklearn import neighbors
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn import tree

x1 = dfX.loc[:,dfX.columns!='Label']
x2 = dfX.loc[:,'Label']

model = tree.DecisionTreeClassifier(max_depth=3)
model.fit(x1, x2)
y_pred = model.predict(x1)

print(confusion_matrix(x2, y_pred))
print(metrics.accuracy_score(x2, y_pred))


[[ 18   0   0  28   2   0   0  34   0   0]
 [  2   0   0  75  10   0   0  32   0   0]
 [  2   0   0  53   5   0   0  43   0   0]
 [  1   0   0 110   5   0   0  27   0   0]
 [  1   0   0  37  50   0   0  39   0   0]
 [  0   0   0   0   1   0   0   0   0   0]
 [  1   0   0  53   1   0   0  56   0   0]
 [  2   0   0  43   8   0   0  77   0   0]
 [  2   0   0  13   2   0   0  12   0   0]
 [  0   0   0  17   7   0   0  38   0   3]]
0.2835164835164835


Decition Tree(K-fold)

In [ ]:
from sklearn import datasets
from sklearn import tree
from sklearn.model_selection import cross_val_score

#iris is a dataset in sklearn library

knn= neighbors.KNeighborsClassifier()
model = tree.DecisionTreeClassifier(max_depth=5)

print("\nk-fold cross validation\n************")

Accuracies = cross_val_score(estimator = model,X= dfX.loc[:,dfX.columns!='Label'],y= dfX.loc[:,'Label'],cv= 10)

Avg_Accuracy = Accuracies.mean()
print(Avg_Accuracy)



k-fold cross validation
************


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(


0.2571428571428571


Split training & test sets

In [ ]:
from sklearn import datasets
from sklearn import neighbors

x = dfX.loc[:,dfX.columns!='Label']
y = dfX.loc[:,'Label']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3) 

knn= neighbors.KNeighborsClassifier() 
knn.fit(x_train,y_train)

y_pred = knn.predict(x_test) # Test a model

knn= neighbors.KNeighborsClassifier() 
knn.fit(x_train,y_train) # Create a model
y_pred= knn.predict(x_test) # Test a model

from sklearn.metrics import confusion_matrix
from sklearn import metrics
print(confusion_matrix(y_test, y_pred))
print(metrics.accuracy_score(y_test, y_pred))


[[12  4  3  1  0  0  4  0  0]
 [15  4  2  5  3  4  3  0  1]
 [10  5  1  0  0  5  1  0  1]
 [ 8  2  1 12  1  7  7  0  1]
 [ 9  3  3  5  7  3  3  0  4]
 [ 7  3  5  6  0 12 10  0  0]
 [10  9  1  5  1  2 13  0  0]
 [ 4  0  0  2  1  1  0  0  0]
 [ 9  2  0  1  1  0  5  0  3]]
0.23443223443223443


เปลี่ยน Label จาก 9 เป็น 4

In [ ]:
dfLabelNew = pd.read_excel('/content/drive/My Drive/AI70/ai73/Lyric_LabelNew.xlsx')

In [ ]:
dfNew = pd.DataFrame(X.toarray())
dfNew['Label'] = dfLabelNew.loc[:,'Label']

In [ ]:
print(dfNew['Label'])

0             รัก
1           เศร้า
2        สนุกสนาน
3           เศร้า
4           เศร้า
          ...    
905         เศร้า
906    ให้กำลังใจ
907    ให้กำลังใจ
908           รัก
909      สนุกสนาน
Name: Label, Length: 910, dtype: object


Decition tree

In [ ]:
from sklearn import neighbors
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn import tree

x1 = dfNew.loc[:,dfX.columns!='Label']
x2 = dfNew.loc[:,'Label']

model = tree.DecisionTreeClassifier(max_depth=3)
model.fit(x1, x2)
y_pred = model.predict(x1)


print("\n *Predicted data* \n")
print(y_pred)
print(confusion_matrix(x2, y_pred))
print(metrics.accuracy_score(x2, y_pred))


 *Predicted data* 

['เศร้า' 'เศร้า' 'รัก' 'รัก' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'เศร้า'
 'รัก' 'รัก' 'รัก' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'เศร้า' 'เศร้า'
 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'เศร้า' 'รัก' 'เศร้า' 'เศร้า' 'เศร้า'
 'รัก' 'รัก' 'เศร้า' 'รัก' 'เศร้า' 'รัก' 'รัก' 'รัก' 'รัก' 'เศร้า' 'รัก'
 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'เศร้า' 'รัก' 'รัก' 'เศร้า' 'เศร้า' 'รัก'
 'รัก' 'เศร้า' 'รัก' 'รัก' 'รัก' 'รัก' 'รัก' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก'
 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'เศร้า'
 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'เศร้า' 'รัก' 'รัก' 'เศร้า'
 'เศร้า' 'รัก' 'รัก' 'รัก' 'เศร้า' 'รัก' 'เศร้า' 'รัก' 'เศร้า' 'รัก' 'รัก'
 'เศร้า' 'เศร้า' 'รัก' 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'เศร้า' 'เศร้า' 'รัก'
 'รัก' 'เศร้า' 'รัก' 'เศร้า' 'รัก' 'เศร้า' 'รัก' 'เศร้า' 'รัก' 'เศร้า'
 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'รัก' 'รัก' 'เศร้า' 'รัก'
 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'เศร้า' 'รัก' 'รัก' 'เศร้า' 'รัก'
 'รัก' 'รัก' 'รัก' 'เศร้า' 'เศ

Decition tree (K-fold)


In [ ]:
from sklearn import datasets
from sklearn import neighbors

x = dfNew.loc[:,dfX.columns!='Label']
y = dfNew.loc[:,'Label']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3) 

knn= neighbors.KNeighborsClassifier() 
knn.fit(x_train,y_train)

y_pred = knn.predict(x_test) # Test a model

knn= neighbors.KNeighborsClassifier() 
knn.fit(x_train,y_train) # Create a model
y_pred= knn.predict(x_test) # Test a model

from sklearn.metrics import confusion_matrix
from sklearn import metrics

print("\n *Predicted data* \n")
print(y_pred)
print(confusion_matrix(y_test, y_pred))
print(metrics.accuracy_score(y_test, y_pred))


 *Predicted data* 

['รัก' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'เศร้า' 'รัก' 'รัก' 'รัก' 'รัก'
 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'รัก' 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า'
 'ให้กำลังใจ' 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'รัก' 'เศร้า'
 'เศร้า' 'รัก' 'รัก' 'สนุกสนาน' 'เศร้า' 'รัก' 'เศร้า' 'เศร้า' 'เศร้า'
 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'เศร้า' 'เศร้า' 'เศร้า'
 'เศร้า' 'รัก' 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'รัก'
 'เศร้า' 'เศร้า' 'เศร้า' 'ให้กำลังใจ' 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า'
 'รัก' 'รัก' 'รัก' 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'เศร้า' 'เศร้า' 'รัก'
 'เศร้า' 'รัก' 'เศร้า' 'เศร้า' 'รัก' 'รัก' 'รัก' 'เศร้า' 'รัก' 'รัก'
 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'เศร้า' 'เศร้า' 'เศร้า'
 'เศร้า' 'เศร้า' 'รัก' 'สนุกสนาน' 'รัก' 'เศร้า' 'รัก' 'เศร้า' 'รัก' 'รัก'
 'รัก' 'รัก' 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'เศร้า' 'เศร้า'
 'ให้กำลังใจ' 'เศร้า' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'เศร้า' 'รัก' 'เศร้า'
 'รัก' 'เศร้า' 'เศร้า' 'เศร้า' 'รัก' 'เศร้า' 'ร

Split training & test sets

In [ ]:
from sklearn import datasets
from sklearn import neighbors

x = dfNew.loc[:,dfX.columns!='Label']
y = dfNew.loc[:,'Label']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3) 

knn= neighbors.KNeighborsClassifier() 
knn.fit(x_train,y_train)

y_pred = knn.predict(x_test) # Test a model

knn= neighbors.KNeighborsClassifier() 
knn.fit(x_train,y_train) # Create a model
y_pred= knn.predict(x_test) # Test a model

from sklearn.metrics import confusion_matrix
from sklearn import metrics
print(confusion_matrix(y_test, y_pred))
print(metrics.accuracy_score(y_test, y_pred))


[[50  1 53  2]
 [19  0 24  2]
 [37  0 58  0]
 [11  0 12  4]]
0.41025641025641024
